### ISSUE TITLE
AttributeError: module 'responses' has no attribute '_is_string'

### ISSUE THREAD

**Issue by val-sytch** [getsentry/responses#501]
I have such versions of packages in the project
boto3==1.17.57
requests ==2.22.0
moto==1.3.14(which has dependency on the latest version of 'responses')

### Steps to Reproduce
I wrote a test to highlight the error.
It works with responses==0.17.0 and doesn't with responses==0.18.0
```
import boto3
import requests
from moto import mock_s3

@mock_s3
def test():
    bucket = 'source_test'
    key = 'raw_data/123.csv.gz'
    boto3.setup_default_session()
    conn = boto3.resource('s3', region_name='us-east-1')
    conn.create_bucket(Bucket='source_test')
    expected_file_content = 'Some bytes data'
    data = bytes(expected_file_content, 'utf-8')
    expected_compressed = gzip.compress(data, 9)
    source_file = conn.Object(
        bucket,
        key,
    )
    source_file.put(Body=expected_compressed)

    client = boto3.client('s3')
    report_url = client.generate_presigned_url(
        'get_object',
        Params={
            'Bucket': bucket,
            'Key': key,
        },
        ExpiresIn=10,
    )
    resp = requests.get(url=report_url, stream=True, timeout=10)
```

### Expected Result

Test works

### Actual Result

it fails with AttributeError: module 'responses' has no attribute '_is_string'
```
============================= test session starts ==============================
collecting ... collected 1 item

test_test.py::test FAILED                                            [100%]
tests/dsp/test_test.py:81 (test)
@mock_s3
    def test():
        bucket = 'source_test'
        key = 'raw_data/123.csv.gz'
        boto3.setup_default_session()
        conn = boto3.resource('s3', region_name='us-east-1')
        conn.create_bucket(Bucket='source_test')
        expected_file_content = 'Some bytes data'
        data = bytes(expected_file_content, 'utf-8')
        expected_compressed = gzip.compress(data, 9)
        source_file = conn.Object(
            bucket,
            key,
        )
        source_file.put(Body=expected_compressed)
    
        client = boto3.client('s3')
        report_url = client.generate_presigned_url(
            'get_object',
            Params={
                'Bucket': bucket,
                'Key': key,
            },
            ExpiresIn=10,
        )
>       resp = requests.get(url=report_url, stream=True, timeout=10)

test_test.py:107: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../venv/lib/python3.7/site-packages/requests/api.py:75: in get
    return request('get', url, params=params, **kwargs)
../../venv/lib/python3.7/site-packages/requests/api.py:60: in request
    return session.request(method=method, url=url, **kwargs)
../../venv/lib/python3.7/site-packages/requests/sessions.py:533: in request
    resp = self.send(prep, **send_kwargs)
../../venv/lib/python3.7/site-packages/requests/sessions.py:646: in send
    r = adapter.send(request, **kwargs)
../../venv/lib/python3.7/site-packages/responses/__init__.py:757: in unbound_on_send
    return self._on_request(adapter, request, *a, **kwargs)
../../venv/lib/python3.7/site-packages/responses/__init__.py:704: in _on_request
    match, match_failed_reasons = self._find_match(request)
../../venv/lib/python3.7/site-packages/responses/__init__.py:687: in _find_match
    return self._registry.find(request)
../../venv/lib/python3.7/site-packages/responses/registries.py:32: in find
    match_result, reason = response.matches(request)
../../venv/lib/python3.7/site-packages/responses/__init__.py:301: in matches
    if not self._url_matches(self.url, request.url):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <moto.core.models.CallbackResponse object at 0x12542fbd0>
url = re.compile('https?://s3(.*).amazonaws.com/$')
other = 'https://s3.amazonaws.com/source_test/raw_data/123.csv.gz'
match_querystring = False

    def _url_matches(self, url, other, match_querystring=False):
        """
        Need to override this so we can fix querystrings breaking regex matching
        """
        if not match_querystring:
            other = other.split("?", 1)[0]
    
>       if responses._is_string(url):
E       AttributeError: module 'responses' has no attribute '_is_string'

../../venv/lib/python3.7/site-packages/moto/core/models.py:198: AttributeError
```

**Comment by bblommers** [comment]
Hi @val-sytch, Moto developer here. We only removed the code that depends on `_is_string` in 2.3.2. So either upgrading Moto (`>= 2.3.2`) or downgrading responses (`<= 0.17.0`) might be your best bet here.

**Comment by val-sytch** [comment]
Hi @bblommers. Thank you for the response. 
Yes, I'll pin `responses<= 0.17.0` in my code but moto==1.3.14 - this version has unpinned dependency to the responses package. Is it possible to pin it inside moto package?

**Comment by bblommers** [comment]
There is no way for us to retroactively pin `responses` for a version that's already released, I'm afraid. Pinning it yourself would be the only way.

This doesn't help you much, I suppose, but as an FYI, in Moto's latest version, we do explicitly support all `responses`-versions.

**Comment by markstory** [comment]
Closing as moto was using internals of responses that were removed. As you've figured out, you'll either need to pin responses or upgrade moto.
