### ISSUE TITLE
getting an error in version 0.10.9 which is solved if I downgrade to 0.10.7

### ISSUE THREAD

**Issue by prakashselvam** [getsentry/responses#292]
self = <RequestsCookieJar[]>, response = <requests.cookies.MockResponse object at 0x7f45f4e76f60>, request = <requests.cookies.MockRequest object at 0x7f45f4e76e48>

    def make_cookies(self, response, request):
        """Return sequence of Cookie objects extracted from response object."""
        # get cookie-attributes for RFC 2965 and Netscape protocols
        headers = response.info()
>       rfc2965_hdrs = headers.get_all("Set-Cookie2", [])
E       AttributeError: 'HTTPHeaderDict' object has no attribute 'get_all'

**Comment by markstory** [comment]
How can I reproduce the error you're seeing?

**Comment by j-san** [comment]
Hi, I just faced the same issue, updating the `requests` version solve it.

**Comment by fgsalomon** [comment]
I'm facing this issue and I can reproduce it with the sample code from the readme:

```Python
import responses
import requests

@responses.activate
def test_simple():
    responses.add(responses.GET, 'http://twitter.com/api/1/foobar',
                  json={'error': 'not found'}, status=404)

    resp = requests.get('http://twitter.com/api/1/foobar')

    assert resp.json() == {"error": "not found"}

    assert len(responses.calls) == 1
    assert responses.calls[0].request.url == 'http://twitter.com/api/1/foobar'
    assert responses.calls[0].response.text == '{"error": "not found"}'
```

I'm using Python 3.6. With version 0.10.7 this code works with versions >0.10.9 it raises that `AttributeError`:

```
self = <RequestsCookieJar[]>, response = <requests.cookies.MockResponse object at 0x7f82221046a0>, request = <requests.cookies.MockRequest object at 0x7f8222104630>

    def make_cookies(self, response, request):
        """Return sequence of Cookie objects extracted from response object."""
        # get cookie-attributes for RFC 2965 and Netscape protocols
        headers = response.info()
>       rfc2965_hdrs = headers.get_all("Set-Cookie2", [])
E       AttributeError: 'HTTPHeaderDict' object has no attribute 'get_all'

```
It doesn't matter which version of `requests` I'm using. I tried with `2.18.0`, `2.22.0` and `2.24.0`.

**Comment by markstory** [comment]
Interesting we run CI against Python 3.6. What does your pip freeze look like?

**Comment by fgsalomon** [comment]
> Interesting we run CI against Python 3.6. What does your pip freeze look like?

Yes, my bad. On a new conda environment it works out the box. It looks that the problem is caused by one of our project dependencies that is forcing 1.21.1 version of urllib3.

**Comment by GlobularMass** [comment]
I was having the same problem, the fix for me was to force upgrade urllib3 to 1.25.10.  Shouldn't responses have a urllib3 min version requirement to avoid this in the future?
